# Site settings
title: Open-Data-Visualisations
email: email@email.com
description: > Data exploration tools and visualisations based on 
	information published on https://opendata.government.bg
baseurl: "/data-viz"
url: ""
exclude: ['README.md','_site']

# Build settings
markdown: kramdown
